import string
table = str.maketrans({key: None for key in string.punctuation})

frag1 = open('fragment1.txt')
frag1 = frag1.read()
frag1 = str(frag1)
frag1s = frag1.translate(table)
frag1ss = "".join(frag1s.split())

frag2 = open('fragment2.txt')
frag2 = frag2.read()
frag2 = str(frag2)
frag2s = frag2.translate(table)
frag2ss = "".join(frag2s.split())

frag3 = open('fragment3.txt')
frag3 = frag3.read()
frag3 = str(frag3)
frag3s = frag3.translate(table)
frag3ss = "".join(frag3s.split())

frag4 = open('fragment4.txt')
frag4 = frag4.read()
frag4 = str(frag4)
frag4s = frag4.translate(table)
frag4ss = "".join(frag4s.split())

frag5 = open('fragment5.txt')
frag5 = frag5.read()
frag5 = str(frag5)
frag5s = frag5.translate(table)
frag5ss = "".join(frag5s.split())

frag6 = open('fragment6.txt')
frag6 = frag6.read()
frag6 = str(frag6)
frag6s = frag6.translate(table)
frag6ss = "".join(frag6s.split())

suspect1 = open('suspect1.txt')
suspect1 = suspect1.read()
suspect1rs = str(suspect1)
suspect1s = suspect1rs.translate(table)
suspect1ss = "".join(suspect1s.split())

suspect2 = open('suspect2.txt')
suspect2 = suspect2.read()
suspect2rs = str(suspect2)
suspect2s = suspect2rs.translate(table)
suspect2ss = "".join(suspect2s.split())

suspect3 = open('suspect3.txt')
suspect3 = suspect3.read()
suspect3rs = str(suspect3)
suspect3s = suspect3rs.translate(table)
suspect3ss = "".join(suspect3s.split())

suspect4 = open('suspect4.txt')
suspect4 = suspect4.read()
suspect4rs = str(suspect4)
suspect4s = suspect4rs.translate(table)
suspect4ss = "".join(suspect4s.split())

suspect5 = open('suspect5.txt')
suspect5 = suspect5.read()
suspect5rs = str(suspect5)
suspect5s = suspect5rs.translate(table)
suspect5ss = "".join(suspect5s.split())

print('Subject 1')
print('Fragment 1 begins at'), [suspect1ss].index(frag1ss)
print('Fragment 2 begins at'), [suspect1ss].index(frag2ss)
print('Fragment 3 begins at'), [suspect1ss].index(frag3ss)
print('Fragment 4 begins at'), [suspect1ss].index(frag4ss)
print('Fragment 5 begins at'), [suspect1ss].index(frag5ss)
print('Fragment 6 begins at'), [suspect1ss].index(frag6ss)

print('\n', '\n')

print('Suspect 2')
print('Fragment 1 begins at'), [suspect2ss].index(frag1ss)
print('Fragment 2 begins at'), [suspect2ss].index(frag2ss)
print('Fragment 3 begins at'), [suspect2ss].index(frag3ss)
print('Fragment 4 begins at'), [suspect2ss].index(frag4ss)
print('Fragment 5 begins at'), [suspect2ss].index(frag5ss)
print('Fragment 6 begins at'), [suspect2ss].index(frag6ss)

print('\n', '\n')

print('Suspect 3')
print('Fragment 1 begins at'), [suspect3ss].index(frag1ss)
print('Fragment 2 begins at'), [suspect3ss].index(frag2ss)
print('Fragment 3 begins at'), [suspect3ss].index(frag3ss)
print('Fragment 4 begins at'), [suspect3ss].index(frag4ss)
print('Fragment 5 begins at'), [suspect3ss].index(frag5ss)
print('Fragment 6 begins at'), [suspect3ss].index(frag6ss)

print('\n', '\n')

print('Suspect 4')
print('Fragment 1 begins at'), [suspect4ss].index(frag1ss)
print('Fragment 2 begins at'), [suspect4ss].index(frag2ss)
print('Fragment 3 begins at'), [suspect4ss].index(frag3ss)
print('Fragment 4 begins at'), [suspect4ss].index(frag4ss)
print('Fragment 5 begins at'), [suspect4ss].index(frag5ss)
print('Fragment 6 begins at'), [suspect4ss].index(frag6ss)

print('\n', '\n')

print('Suspect 5')
print('Fragment 1 begins at'), [suspect5ss].index(frag1ss)
print('Fragment 2 begins at'), [suspect5ss].index(frag2ss)
print('Fragment 3 begins at'), [suspect5ss].index(frag3ss)
print('Fragment 4 begins at'), [suspect5ss].index(frag4ss)
print('Fragment 5 begins at'), [suspect5ss].index(frag5ss)
print('Fragment 6 begins at'), [suspect5ss].index(frag6ss)